# Generated by Django 3.2.14 on 2023-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category', models.CharField(choices=[('FreshGoods', 'FreshGoods'), ('Groceries', 'Groceries'), ('Provision', 'Provision'), ('Cosmetics', 'Cosmetics'), ('Beverages', 'Beverages'), ('Bakeries', 'Bakeries'), ('Other', 'Other')], max_length=255)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Product_unit_Price', models.CharField(max_length=255)),
                ('Product_Brand', models.CharField(max_length=255)),
                ('Product_Stock', models.CharField(max_length=255)),
                ('Batch_Code', models.CharField(max_length=255)),
                ('Expairy_Date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
