# Generated by Django 3.2.14 on 2023-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_Image',
            field=models.FileField(default=0, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
