# Generated by Django 3.2.14 on 2023-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='GST',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
