# Generated by Django 3.2.14 on 2023-03-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vender_name', models.CharField(max_length=255)),
                ('Vender_Poducts', models.CharField(max_length=255)),
                ('Vender_Product_Cat', models.CharField(choices=[('FreshGoods', 'FreshGoods'), ('Groceries', 'Groceries'), ('Provision', 'Provision'), ('Cosmetics', 'Cosmetics'), ('Beverages', 'Beverages'), ('Bakeries', 'Bakeries'), ('Other', 'Other')], max_length=255)),
                ('Vender_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='vender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.venders'),
        ),
    ]
